### PR TITLE
Display CSV and ASCII table LDM-240 extracts on the web.

### PR DESCRIPTION
**Pull request by jdswinbank**

### CODE REVIEW

**Comment by timj** [comment]
Couldn't jira2text be in jirakit.py? Why does it need its own file?

**Comment by jdswinbank** [comment]
`jira2dot` is already in its own file. Consistency seems like a virtue, but I don't have strong opinions either way.

**Comment by timj** [comment]
Can always worry about it later. My assumption was that `jirakit` was for the JIRA support functions for SQuaRE.

**Comment by frossie** [comment]
I am not at all bothered as to whether people's jira-related stuff is in jirakit or not. People can use it or not, whatever is easiest for them. The purpose for jirakit.py is that cut-and-pasted code burnsss ussss and _I_ need somewhere to put stuff when I catch myself doing it.

**Pull request merged**
