### PR TITLE
Add utility to insert epics for KPMs

### PR DESCRIPTION
**Pull request by SimonKrughoff**
This utility is supposed to make it a little easier to add KPM values.  I don't have a unit test since it requires all sorts of connectivity and such, but if it's necessary I can add one.

### CODE REVIEW

**Comment by jdswinbank** [comment]
Please let's not start requiring tests or code reviews or anything like that here. It's a useful dumping ground for quick scripts which might be generally useful, but I don't want to invest a lot of time on polishing them up.

That said... my concern about Simon's PR here is that it brings in a dependency on `lsst.daf`, which makes things complicated in a couple of ways:
- One can no longer just do "pip install" per the README and expect things to work;
- If `lsst.sqre` ends up on your `$PYTHONPATH` ahead of the rest of `lsst`, it'll mask out everything else (because we don't do the `pkgutil.extend()` dance in `lsst-sqre`'s `__init__.py`). And then `add_kpm_epics.py` will break, because it can't import `DbAuth`.

Also, it's probably worth adding `add_kpm_epics.py` to the `scripts` line in `setup.py`.

**Comment by jdswinbank** [comment]
(Should add that I don't intend the above to torpedo this PR -- I think it's just a matter of tweaking the docs and maybe `__init__.py` to reflect what's going on.)

**Comment by SimonKrughoff** [comment]
My mention of a unit test should not be interpreted as my desire to write one :)  

Regarding the dependence on daf, I hadn't thought about those negative effects.  I'm happy to remove it and do something hackier.  The other option is that we go the OAUTH route.

**Comment by timj** [comment]
Well, you have a fall back in the code so just moving the `DBAuth` import to the relevant `try` block later on would solve it. But yes, a shared token would be better now that @frossie has worked it out.

**Comment by jdswinbank** [comment]
I'd love to see a demo of how OAuth would work here, as I've not really understood it yet.

Beside that, I don't think that there's a problem here that merits taking the `daf` dependency out. Add a note to the README, maybe add the `pkgutil` thing in `__init__.py` (would that help? I'm not sure off hand), use an exception handler.

**Comment by SimonKrughoff** [comment]
O.K.  So I removed the dependency on daf_persistence.  I don't have perms to merge this, but I think it should be.

**Pull request merged**
